### ISSUE TITLE
error MSB3073 exited with code -1

### ISSUE THREAD

**Issue by lurchinms** [oliverw/miningcore#1311]
Fresh install on Ubuntu 20.04.
I also reinstall Ubuntu 20.04 and have the same error.

rm -f librandomarq.so
  g++   -shared -pthread -L. -Wl,-whole-archive librandomx.a -Wl,-no-whole-archive -o librandomarq.so  -lstdc++ -lgcc -lc
/home/XXXXXXXX/miningcore/src/Miningcore/Miningcore.csproj(123,9): error MSB3073: The command "(cd /home/XXXXXXXX/miningcore/src/Miningcore/ && sh build-libs-linux.sh bin/Release/net6.0/)" exited with code -1.

**Comment by oliverw** [comment]
All dependencies installed?

**Comment by lurchinms** [comment]
Used the 
build-ubuntu-20.04.sh

**Comment by oliverw** [comment]
> Same error on manual build as well.

I can't be the same error as MSBUILD is not involved when running make individually.

**Comment by lurchinms** [comment]
I am sorry, when I say manual build, I meant:
dotnet publish -c Release --framework net6.0  -o ../../build

**Comment by lurchinms** [comment]
Won't build on Ubuntu 21 either. Same error MSB3073.

**Comment by lurchinms** [comment]
/usr/lib/gcc/x86_64-linux-gnu/11/include/avx2intrin.h(913,1): error G2ABF96FA: inlining failed in call to 'always_inline' '__m256i _mm256_xor_si256(__m256i, __m256i)': target specific option mismatch [/home/XXXXXXXX
/miningcore/src/Miningcore/Miningcore.csproj]

**Comment by lurchinms** [comment]
Must be a Microsoft dotnet issue, maybe some update. I tried build it on a different server using Ubuntu 18.04 and get the same error.

**Comment by oliverw** [comment]
> /usr/lib/gcc/x86_64-linux-gnu/11/include/avx2intrin.h(913,1): error G2ABF96FA: inlining failed in call to 'always_inline' '__m256i _mm256_xor_si256(__m256i, __m256i)': target specific option mismatch [/home/XXXXXXXX /miningcore/src/Miningcore/Miningcore.csproj]

That is a GCC error. Not a Microsoft error. Could you please try what I outlined above?

**Comment by oliverw** [comment]
Does it still happen with the latest `dev` branch?

**Comment by lurchinms** [comment]
I perform fresh Ubuntu 21.04 install and installed using the build-ubuntu-21.04.sh and it performed the same error.

**Comment by lurchinms** [comment]
I think the problem is inside the XMR  build.

**Comment by oliverw** [comment]
I cannot reproduce this problem on any system.

**Comment by lurchinms** [comment]
> I cannot reproduce this problem on any system.

On fresh server installs?

**Comment by lurchinms** [comment]
build-libs-linux.sh
Line 30 is not building the Native folder.

**Comment by lurchinms** [comment]
I think the error is in the build-libs-linux.sh for RandomX. 
I will test further when I get home from work this evening.

**Comment by makertronic** [comment]
hello, 
I'm on debian 11 and i got this error too : 
3randomx_cache]+0x28): undefined reference to `randomx::JitCompilerX86::~JitCompilerX86()'
  /usr/bin/ld: librandomx.a(dataset.cpp.o): in function `void randomx::deallocCache<randomx::LargePageAllocator>(randomx_cache*)':
  dataset.cpp:(.text._ZN7randomx12deallocCacheINS_18LargePageAllocatorEEEvP13randomx_cache[_ZN7randomx12deallocCacheINS_18LargePageAllocatorEEEvP13randomx_cache]+0x28): undefined reference to `randomx::JitCompilerX86::~JitCompilerX86()'
collect2 : error : ld returned 1 exit status [/home/nicola/miningcore/src/Miningcore/Miningcore.csproj]
  make[2]: *** [CMakeFiles/randomx-benchmark.dir/build.make:119: randomx-benchmark] Error 1
  make[1]: *** [CMakeFiles/Makefile2:101: CMakeFiles/randomx-benchmark.dir/all] Error 2
  make: *** [Makefile:149: all] Error 2
/home/nicola/miningcore/src/Miningcore/Miningcore.csproj(123,9): error MSB3073: La commande "(cd /home/nicola/miningcore/src/Miningcore/ && sh build-libs-linux.sh bin/Release/net6.0/)" s'est arrêtée avec le code 2.

**Comment by oliverw** [comment]
I suspect both of you are running on CPUs which are missing instruction extensions required to compile RandomX.

**Comment by makertronic** [comment]
maybe, here my CPU : 
processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
stepping        : 3
microcode       : 0x28
cpu MHz         : 2537.699
cache size      : 6144 KB
physical id     : 0
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 6
initial apicid  : 6
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds

**Comment by makertronic** [comment]
anyway, can we remove support for RandomX ?

**Comment by oliverw** [comment]
Sure, just comment out the last two lines inside build-libs-linux.sh and try again. Let me know how it went and obviously don't try to use any Cryptonight Family coin (Monero etc) with your pool.

**Comment by makertronic** [comment]
it worked !
So maybe it was my poor cpu :)

**Comment by makertronic** [comment]
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/85033212/179362308-5780b35c-99a4-4e47-b6ce-cfc3f5753b84.png">

**Comment by lurchinms** [comment]
Hmmm. I will do more research on this issue.
![image](https://user-images.githubusercontent.com/12227665/179373366-45a7aa3a-6419-444f-b3d3-dd254a18b9ef.png)

**Comment by oliverw** [comment]
> Hmmm. I will do more research on this issue. ![image](https://user-images.githubusercontent.com/12227665/179373366-45a7aa3a-6419-444f-b3d3-dd254a18b9ef.png) I pretty sure this can run it.

I agree.

**Comment by lurchinms** [comment]
I ended up going to an older build.
Before Commits on May 27, 2022

**Comment by minershaven** [comment]
> I ended up going to an older build. Before Commits on March 11, 2022

i had to do the same thing.  got that same error using ubuntu 18 and 20.

**Comment by minershaven** [comment]
I have tried the new version on Ubuntu 18 and 20 as well as trying to build it on windows and get the same error each time. Something with the Randomx algorithm is stopping it.

**Comment by 3djc** [comment]
I faced the same issue, but reading the previous comment, it became clear the issue was with the CPU not handling all the required instruction set for Randomx? Since it was a self hosted VM, I changed CPU type from "kvm64" to "host", and that game me the required CPU functions and it did compile (and run) successfully. Of course, one could hope a much clearer error message, or conditional inclusion of randomx based on CPU generation

**Comment by minershaven** [comment]
my cpu should be fine.  ive tried it on my servers which have Xeon(R) E3-1231 v3 @ 3.40GHz cpu's and i even tried the windows build on my home pc which has a i9-10980xe so that shouldn't be whats preventing me from building it.  I even tried taking out the RandomX part of the install as Oliver suggested earlier but still nothing.   The error i'm getting, 
`g++ -shared -pthread -L. -Wl,-whole-archive librandomx.a -Wl,-no-whole-archive -o librandomarq.so -lstdc++ -lgcc -lc
/home/XXXXXXXX/miningcore/src/Miningcore/Miningcore.csproj(123,9): error MSB3073: The command "(cd /home/XXXXXXXX/miningcore/src/Miningcore/ && sh build-libs-linux.sh bin/Release/net6.0/)" exited with code -1.`

looks to me like its an issue with the `bin/Release/net6.0/` folder.  dont know if it's a permission issue or if it doesnt exsist but it looks like the issue is there.

Or i could be completely wrong, who knows

**Comment by minershaven** [comment]
havent been able to fix it but i did find a workaround for it.  everything gets built to 
`/Miningcore/bin/Release/net6.0`  folder so i just copied everything in there to the build folder and everything is working fine now.

**Comment by machinasapiens** [comment]
I am running into this same problem and believe issu #1327  is also related to this.

**Comment by seperatis** [comment]
@lurchinms @machinasapiens 

Is this resolved?

**Comment by lurchinms** [comment]
@seperatis I am using previous version of the code., before he made that LINUX build file.

**Comment by seperatis** [comment]
@oliverw Did we find the cause of this? Is it the build script or CPU's not supported, etc?

**Comment by seperatis** [comment]
> @seperatis I am using previous version of the code., before he made that LINUX build file.

@lurchinms and is that version running XMR pool without any issues?

**Comment by machinasapiens** [comment]
> @lurchinms @machinasapiens
> 
> Is this resolved?

[SOLVED] #1350

**Comment by RichardWTexcel** [comment]
> > @lurchinms @machinasapiens
> > Is this resolved?
> 
> [SOLVED] #1350

Sorry mate, not solved...

/home/<Sensored>/miningcore/src/Miningcore/Miningcore.csproj(123,9): error MSB3073: The command "(cd /home/<Sensored>/miningcore/src/Miningcore/ && sh build-libs-linux.sh bin/Release/net6.0/)" exited with code -1.

**Comment by machinasapiens** [comment]
> 



> Sorry mate, not solved...
> /home//miningcore/src/Miningcore/Miningcore.csproj(123,9): error MSB3073: The command "(cd /home//miningcore/src/Miningcore/ && sh build-libs-linux.sh bin/Release/net6.0/)" exited with code -1.

I solved it but the maintainer of this repository did not publish my contribution as you can see in the image below. 

If you can not wait what you can do is get the fixed code from my fork at https://github.com/machinasapiens/miningcore

Good luck.

![image](https://user-images.githubusercontent.com/111072336/187029146-4492e248-4b2b-4674-90c7-7118967617ae.png)

**Comment by machinasapiens** [comment]
Pull request #1350 closed due to lack of answer from the maintainer of this repository in the last 13 days.

**Comment by seperatis** [comment]
> Pull request #1350 closed due to lack of answer from the maintainer of this repository in the last 13 days.

I'll re-open the pull request and assign it to OliverW for review, I'm not going to merge it into the main branch until OliverW looks at it. If it were Dev branch I'd would have committed it, but I need his eyeballs on main branch things.

In practice, in the future, If you think your solution is correct, don't close your pull request. This is open source software, with not a lot of active developers.... OliverW (lead Dev) has other employment and family obligations - that means sometimes he does lots of work on Miningcore for days or weeks straight, and then sometimes he doesn't make an appearance for a month. 

It also depends on the severity of the issue at hand. We're talking about build scripts here - if this were a critical bug in the code, he'd have made time to review that.

Anyways, thanks for your contribution, I've re-opened the pull request and assigned it to OliverW for review.

**Comment by RichardWTexcel** [comment]
> > Sorry mate, not solved...
> > /home//miningcore/src/Miningcore/Miningcore.csproj(123,9): error MSB3073: The command "(cd /home//miningcore/src/Miningcore/ && sh build-libs-linux.sh bin/Release/net6.0/)" exited with code -1.
> 
> I solved it but the maintainer of this repository did not publish my contribution #1350 as you can see in the image below.
> 
> If you can not wait what you can do is get the fixed code from my fork at https://github.com/machinasapiens/miningcore
> 
> Good luck.
> 
> ![image](https://user-images.githubusercontent.com/111072336/187029146-4492e248-4b2b-4674-90c7-7118967617ae.png)

I manually updated the build-debian-11.sh with your changes with the same result, is there more to it?

**Comment by machinasapiens** [comment]
> I manually updated the build-debian-11.sh with your changes and got the same result, is there more to it?

You ALSO need this corrected file, otherwise the error will persist:
https://github.com/machinasapiens/miningcore/blob/master/src/Miningcore/Miningcore.csproj

How I fixed this problem: I added line 124 and commented out line 123 which was calling build-libs-linux.sh . I placed the call to build-libs-linux.sh inside the files build-debian-11.sh ,  build-ubuntu-20.04.sh and build-ubuntu-21.04.sh.  This way they run outside of the "dotnet publish" command and do not crash anymore. The crash was being caused by some problem with char encoding.

**Comment by oliverw** [comment]
Would love to accept the PR but currently the tests are failing in CI.

**Comment by machinasapiens** [comment]
> 

Just leave ithe PR or now. I'll fork and fix it later again using the online VS editor and then you try again. I'm busy with a rocket launch now. Take care.

**Comment by oliverw** [comment]
Please retest with `dev` branch.

**Comment by machinasapiens** [comment]
@oliverw dev branch tested:

![image](https://user-images.githubusercontent.com/111072336/190922583-75c2a7d2-94c0-41be-85bf-fadc6a9dce2e.png)

**Comment by oliverw** [comment]
This is so weird as it works in CI -> https://github.com/oliverw/miningcore/actions/runs/3077548067

**Comment by machinasapiens** [comment]
![image](https://user-images.githubusercontent.com/111072336/190922683-66548dea-be24-46dc-a0a1-5e91ae45a85b.png)

**Comment by machinasapiens** [comment]
> This is so weird as it works in CI -> https://github.com/oliverw/miningcore/actions/runs/3077548067

The build-XXXXX.sh files are running a different sequence of commands than the CI

I am manually repeating the CI sequence here now to see what happens

**Comment by machinasapiens** [comment]
@oliverw  I made a minor change to Miningcore.csproj. Please check #1413 . It is building fine now on Ubuntu 20.04 by running  build-ubuntu-20.04.sh

**Comment by machinasapiens** [comment]
@oliverw  I made a minor change at line 123 of Miningcore.csproj. Please check #1413 . Tested here on Ubuntu 20.04 by running build-ubuntu-20.04.sh and worked fine. Now all the build-XXXX.sh files for Debian based distros should be working. This shall solve issues #1311 and #1327. Please test.

![image](https://user-images.githubusercontent.com/111072336/190925716-bad66da9-905c-4f7c-8a9d-fde9be3d8607.png)

**Comment by oliverw** [comment]
> @oliverw I made a minor change at line 123 of Miningcore.csproj. Please check #1413 . Tested here on Ubuntu 20.04 by running build-ubuntu-20.04.sh and worked fine. Now all the build-XXXX.sh files for Debian based distros should be working. This shall solve issues #1311 and #1327. Please test.
> 
> ![image](https://user-images.githubusercontent.com/111072336/190925716-bad66da9-905c-4f7c-8a9d-fde9be3d8607.png)

Seen it but not sure if is simply ignoring the error is the play here 😄

**Comment by machinasapiens** [comment]
@oliverw There are no errors if you run the command "(cd /root/miningcore-dev/src/Miningcore/ && sh build-libs-linux.sh bin/Release/net6.0/)" separatelly. 

I am sending you the logs --

 [build-logs.zip](https://github.com/oliverw/miningcore/files/9595186/build-logs.zip)

**Comment by oliverw** [comment]
> @oliverw There are no errors if you run the line 123 of Miningcore.csproj command separatelly, in my case "(cd /root/miningcore-dev/src/Miningcore/ && sh build-libs-linux.sh bin/Release/net6.0/)".
> 
> The call to build-libs-linux.sh by donet is generating a -1 exit code, that in fact does not exist.
> 
> I am sending you the logs --
> 
> [build-logs.zip](https://github.com/oliverw/miningcore/files/9595186/build-logs.zip)

Well, the well known `target specific option mismatch` error still happens at line 214 of `build-ubuntu-20.04.log`. So it's not a phantom error.

**Comment by machinasapiens** [comment]
> > @oliverw There are no errors if you run the line 123 of Miningcore.csproj command separatelly, in my case "(cd /root/miningcore-dev/src/Miningcore/ && sh build-libs-linux.sh bin/Release/net6.0/)".
> > The call to build-libs-linux.sh by donet is generating a -1 exit code, that in fact does not exist.
> > I am sending you the logs --
> > [build-logs.zip](https://github.com/oliverw/miningcore/files/9595186/build-logs.zip)
> 
> Well, the well known `target specific option mismatch` error still happens at line 214 of `build-ubuntu-20.04.log`. So it's not a phantom error.

Nice you found it. You're welcome.

**Comment by oliverw** [comment]
> > > @oliverw There are no errors if you run the line 123 of Miningcore.csproj command separatelly, in my case "(cd /root/miningcore-dev/src/Miningcore/ && sh build-libs-linux.sh bin/Release/net6.0/)".
> > > The call to build-libs-linux.sh by donet is generating a -1 exit code, that in fact does not exist.
> > > I am sending you the logs --
> > > [build-logs.zip](https://github.com/oliverw/miningcore/files/9595186/build-logs.zip)
> > 
> > 
> > Well, the well known `target specific option mismatch` error still happens at line 214 of `build-ubuntu-20.04.log`. So it's not a phantom error.
> 
> Nice you found it. You're welcome.

Are you trolling me?

**Comment by oliverw** [comment]
Please request re-open if problem persists using latest `dev` branch.
